sylius_admin_order_creation_ajax_customer:
    path: /customer-search
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer::indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findByEmailPart
                arguments: $email

sylius_admin_order_creation_ajax_customer_by_email:
    path: /customer-search-by-email
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer::indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findBy
                arguments: [email: $email]

sylius_admin_order_creation_ajax_product_variants_by_phrase_and_channel:
    path: /product-variant-search/{channelCode}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant::indexAction
        _format: json
        _sylius:
            permission: true
            serialization_groups: [Autocomplete]
            repository:
                method: findByPhraseAndChannelCode
                arguments:
                    phrase: $phrase
                    channelCode: $channelCode
                    locale: expr:service('sylius.context.locale').getLocaleCode()

sylius_admin_order_creation_ajax_product_variant_by_codes:
    path: /product-variant-search-by-code
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant::indexAction
        _format: json
        _sylius:
            permission: true
            serialization_groups: [Autocomplete]
            repository:
                method: findOneByCode
                arguments: $code

sylius_admin_order_creation_ajax_provide_available_shipping_methods:
    path: /orders/available-shipping-methods/{customerId}/{channelCode}/{shipmentNumber}
    methods: [GET]
    defaults:
        _controller: Sylius\AdminOrderCreationPlugin\Controller\ProvideAvailableShippingMethodsAction
    options:
        expose: true
